apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-mikolai-dev-tls
spec:
  secretName: k8s-mikolai-dev
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mikolai.dev
  dnsNames:
    - mikolai.dev
    - www.mikolai.dev
  acme:
    config:
      - http01: 
          ingresClass: nginx
        domains:
          - mikolai.dev
          - www.mikolai.dev